/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ssavr.solr.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the IceCream service. Represents a row in the &quot;solr_IceCream&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ssavr.solr.model.impl.IceCreamModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ssavr.solr.model.impl.IceCreamImpl}.
 * </p>
 *
 * @author SAVRAMIS
 * @see IceCream
 * @see com.ssavr.solr.model.impl.IceCreamImpl
 * @see com.ssavr.solr.model.impl.IceCreamModelImpl
 * @generated
 */
public interface IceCreamModel extends BaseModel<IceCream> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ice cream model instance should use the {@link IceCream} interface instead.
	 */

	/**
	 * Gets the primary key of this ice cream.
	 *
	 * @return the primary key of this ice cream
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ice cream
	 *
	 * @param primaryKey the primary key of this ice cream
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Gets the uuid of this ice cream.
	 *
	 * @return the uuid of this ice cream
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this ice cream.
	 *
	 * @param uuid the uuid of this ice cream
	 */
	public void setUuid(String uuid);

	/**
	 * Gets the ice cream ID of this ice cream.
	 *
	 * @return the ice cream ID of this ice cream
	 */
	public long getIceCreamId();

	/**
	 * Sets the ice cream ID of this ice cream.
	 *
	 * @param iceCreamId the ice cream ID of this ice cream
	 */
	public void setIceCreamId(long iceCreamId);

	/**
	 * Gets the company ID of this ice cream.
	 *
	 * @return the company ID of this ice cream
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this ice cream.
	 *
	 * @param companyId the company ID of this ice cream
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets the user ID of this ice cream.
	 *
	 * @return the user ID of this ice cream
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this ice cream.
	 *
	 * @param userId the user ID of this ice cream
	 */
	public void setUserId(long userId);

	/**
	 * Gets the user uuid of this ice cream.
	 *
	 * @return the user uuid of this ice cream
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this ice cream.
	 *
	 * @param userUuid the user uuid of this ice cream
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Gets the create date of this ice cream.
	 *
	 * @return the create date of this ice cream
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this ice cream.
	 *
	 * @param createDate the create date of this ice cream
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Gets the modified date of this ice cream.
	 *
	 * @return the modified date of this ice cream
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ice cream.
	 *
	 * @param modifiedDate the modified date of this ice cream
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Gets the flavor of this ice cream.
	 *
	 * @return the flavor of this ice cream
	 */
	@AutoEscape
	public String getFlavor();

	/**
	 * Sets the flavor of this ice cream.
	 *
	 * @param flavor the flavor of this ice cream
	 */
	public void setFlavor(String flavor);

	/**
	 * Gets the name of this ice cream.
	 *
	 * @return the name of this ice cream
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this ice cream.
	 *
	 * @param name the name of this ice cream
	 */
	public void setName(String name);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(IceCream iceCream);

	public int hashCode();

	public CacheModel<IceCream> toCacheModel();

	public IceCream toEscapedModel();

	public String toString();

	public String toXmlString();
}