/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ssavr.solr.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.ssavr.solr.model.IceCream;
import com.ssavr.solr.service.IceCreamLocalServiceUtil;

/**
 * The extended model base implementation for the IceCream service. Represents a row in the &quot;solr_IceCream&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link IceCreamImpl}.
 * </p>
 *
 * @author SAVRAMIS
 * @see IceCreamImpl
 * @see com.ssavr.solr.model.IceCream
 * @generated
 */
public abstract class IceCreamBaseImpl extends IceCreamModelImpl
	implements IceCream {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ice cream model instance should use the {@link IceCream} interface instead.
	 */
	public void persist() throws SystemException {
		IceCreamLocalServiceUtil.updateIceCream(this);
	}
}