/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ssavr.solr.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.ssavr.solr.model.IceCream;
import com.ssavr.solr.model.IceCreamModel;
import com.ssavr.solr.model.IceCreamSoap;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * The base model implementation for the IceCream service. Represents a row in the &quot;solr_IceCream&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ssavr.solr.model.IceCreamModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link IceCreamImpl}.
 * </p>
 *
 * @author SAVRAMIS
 * @see IceCreamImpl
 * @see com.ssavr.solr.model.IceCream
 * @see com.ssavr.solr.model.IceCreamModel
 * @generated
 */
@JSON(strict = true)
public class IceCreamModelImpl extends BaseModelImpl<IceCream>
	implements IceCreamModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ice cream model instance should use the {@link com.ssavr.solr.model.IceCream} interface instead.
	 */
	public static final String TABLE_NAME = "solr_IceCream";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "iceCreamId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "flavor", Types.VARCHAR },
			{ "name", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table solr_IceCream (uuid_ VARCHAR(75) null,iceCreamId LONG not null primary key,companyId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,flavor VARCHAR(75) null,name VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table solr_IceCream";
	public static final String ORDER_BY_JPQL = " ORDER BY iceCream.iceCreamId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY solr_IceCream.iceCreamId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ssavr.solr.model.IceCream"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ssavr.solr.model.IceCream"),
			true);

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static IceCream toModel(IceCreamSoap soapModel) {
		IceCream model = new IceCreamImpl();

		model.setUuid(soapModel.getUuid());
		model.setIceCreamId(soapModel.getIceCreamId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setFlavor(soapModel.getFlavor());
		model.setName(soapModel.getName());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<IceCream> toModels(IceCreamSoap[] soapModels) {
		List<IceCream> models = new ArrayList<IceCream>(soapModels.length);

		for (IceCreamSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public Class<?> getModelClass() {
		return IceCream.class;
	}

	public String getModelClassName() {
		return IceCream.class.getName();
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ssavr.solr.model.IceCream"));

	public IceCreamModelImpl() {
	}

	public long getPrimaryKey() {
		return _iceCreamId;
	}

	public void setPrimaryKey(long primaryKey) {
		setIceCreamId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_iceCreamId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@JSON
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	public void setUuid(String uuid) {
		_uuid = uuid;
	}

	@JSON
	public long getIceCreamId() {
		return _iceCreamId;
	}

	public void setIceCreamId(long iceCreamId) {
		_iceCreamId = iceCreamId;
	}

	@JSON
	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	public String getFlavor() {
		if (_flavor == null) {
			return StringPool.BLANK;
		}
		else {
			return _flavor;
		}
	}

	public void setFlavor(String flavor) {
		_flavor = flavor;
	}

	@JSON
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	public void setName(String name) {
		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@Override
	public IceCream toEscapedModel() {
		if (isEscapedModel()) {
			return (IceCream)this;
		}
		else {
			if (_escapedModelProxy == null) {
				_escapedModelProxy = (IceCream)Proxy.newProxyInstance(_classLoader,
						_escapedModelProxyInterfaces,
						new AutoEscapeBeanHandler(this));
			}

			return _escapedModelProxy;
		}
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
					IceCream.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		IceCreamImpl iceCreamImpl = new IceCreamImpl();

		iceCreamImpl.setUuid(getUuid());
		iceCreamImpl.setIceCreamId(getIceCreamId());
		iceCreamImpl.setCompanyId(getCompanyId());
		iceCreamImpl.setUserId(getUserId());
		iceCreamImpl.setCreateDate(getCreateDate());
		iceCreamImpl.setModifiedDate(getModifiedDate());
		iceCreamImpl.setFlavor(getFlavor());
		iceCreamImpl.setName(getName());

		iceCreamImpl.resetOriginalValues();

		return iceCreamImpl;
	}

	public int compareTo(IceCream iceCream) {
		int value = 0;

		if (getIceCreamId() < iceCream.getIceCreamId()) {
			value = -1;
		}
		else if (getIceCreamId() > iceCream.getIceCreamId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		IceCream iceCream = null;

		try {
			iceCream = (IceCream)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = iceCream.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		IceCreamModelImpl iceCreamModelImpl = this;

		iceCreamModelImpl._originalName = iceCreamModelImpl._name;
	}

	@Override
	public CacheModel<IceCream> toCacheModel() {
		IceCreamCacheModel iceCreamCacheModel = new IceCreamCacheModel();

		iceCreamCacheModel.uuid = getUuid();

		String uuid = iceCreamCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			iceCreamCacheModel.uuid = null;
		}

		iceCreamCacheModel.iceCreamId = getIceCreamId();

		iceCreamCacheModel.companyId = getCompanyId();

		iceCreamCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			iceCreamCacheModel.createDate = createDate.getTime();
		}
		else {
			iceCreamCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			iceCreamCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			iceCreamCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		iceCreamCacheModel.flavor = getFlavor();

		String flavor = iceCreamCacheModel.flavor;

		if ((flavor != null) && (flavor.length() == 0)) {
			iceCreamCacheModel.flavor = null;
		}

		iceCreamCacheModel.name = getName();

		String name = iceCreamCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			iceCreamCacheModel.name = null;
		}

		return iceCreamCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", iceCreamId=");
		sb.append(getIceCreamId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", flavor=");
		sb.append(getFlavor());
		sb.append(", name=");
		sb.append(getName());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.ssavr.solr.model.IceCream");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>iceCreamId</column-name><column-value><![CDATA[");
		sb.append(getIceCreamId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>flavor</column-name><column-value><![CDATA[");
		sb.append(getFlavor());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = IceCream.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			IceCream.class
		};
	private String _uuid;
	private long _iceCreamId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private Date _createDate;
	private Date _modifiedDate;
	private String _flavor;
	private String _name;
	private String _originalName;
	private transient ExpandoBridge _expandoBridge;
	private IceCream _escapedModelProxy;
}