/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ssavr.solr.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.search.Indexer;
import com.liferay.portal.kernel.search.IndexerRegistryUtil;
import com.liferay.portal.kernel.search.SearchException;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import com.liferay.portlet.documentlibrary.service.DLFileEntryLocalService;
import com.liferay.portlet.documentlibrary.service.DLFileEntryService;
import com.liferay.portlet.documentlibrary.service.persistence.DLFileEntryPersistence;

import com.ssavr.solr.model.IceCream;
import com.ssavr.solr.service.IceCreamDocumentsLocalService;
import com.ssavr.solr.service.IceCreamDocumentsService;
import com.ssavr.solr.service.IceCreamLocalService;
import com.ssavr.solr.service.IceCreamService;
import com.ssavr.solr.service.persistence.IceCreamDocumentsPersistence;
import com.ssavr.solr.service.persistence.IceCreamPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the ice cream local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.ssavr.solr.service.impl.IceCreamLocalServiceImpl}.
 * </p>
 *
 * @author SAVRAMIS
 * @see com.ssavr.solr.service.impl.IceCreamLocalServiceImpl
 * @see com.ssavr.solr.service.IceCreamLocalServiceUtil
 * @generated
 */
public abstract class IceCreamLocalServiceBaseImpl
	implements IceCreamLocalService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.ssavr.solr.service.IceCreamLocalServiceUtil} to access the ice cream local service.
	 */

	/**
	 * Adds the ice cream to the database. Also notifies the appropriate model listeners.
	 *
	 * @param iceCream the ice cream
	 * @return the ice cream that was added
	 * @throws SystemException if a system exception occurred
	 */
	public IceCream addIceCream(IceCream iceCream) throws SystemException {
		iceCream.setNew(true);

		iceCream = iceCreamPersistence.update(iceCream, false);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.reindex(iceCream);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}

		return iceCream;
	}

	/**
	 * Creates a new ice cream with the primary key. Does not add the ice cream to the database.
	 *
	 * @param iceCreamId the primary key for the new ice cream
	 * @return the new ice cream
	 */
	public IceCream createIceCream(long iceCreamId) {
		return iceCreamPersistence.create(iceCreamId);
	}

	/**
	 * Deletes the ice cream with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param iceCreamId the primary key of the ice cream
	 * @throws PortalException if a ice cream with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteIceCream(long iceCreamId)
		throws PortalException, SystemException {
		IceCream iceCream = iceCreamPersistence.remove(iceCreamId);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.delete(iceCream);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}
	}

	/**
	 * Deletes the ice cream from the database. Also notifies the appropriate model listeners.
	 *
	 * @param iceCream the ice cream
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteIceCream(IceCream iceCream) throws SystemException {
		iceCreamPersistence.remove(iceCream);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.delete(iceCream);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return iceCreamPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return iceCreamPersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return iceCreamPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return iceCreamPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the ice cream with the primary key.
	 *
	 * @param iceCreamId the primary key of the ice cream
	 * @return the ice cream
	 * @throws PortalException if a ice cream with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public IceCream getIceCream(long iceCreamId)
		throws PortalException, SystemException {
		return iceCreamPersistence.findByPrimaryKey(iceCreamId);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return iceCreamPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the ice creams.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of ice creams
	 * @param end the upper bound of the range of ice creams (not inclusive)
	 * @return the range of ice creams
	 * @throws SystemException if a system exception occurred
	 */
	public List<IceCream> getIceCreams(int start, int end)
		throws SystemException {
		return iceCreamPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of ice creams.
	 *
	 * @return the number of ice creams
	 * @throws SystemException if a system exception occurred
	 */
	public int getIceCreamsCount() throws SystemException {
		return iceCreamPersistence.countAll();
	}

	/**
	 * Updates the ice cream in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param iceCream the ice cream
	 * @return the ice cream that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public IceCream updateIceCream(IceCream iceCream) throws SystemException {
		return updateIceCream(iceCream, true);
	}

	/**
	 * Updates the ice cream in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param iceCream the ice cream
	 * @param merge whether to merge the ice cream with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the ice cream that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public IceCream updateIceCream(IceCream iceCream, boolean merge)
		throws SystemException {
		iceCream.setNew(false);

		iceCream = iceCreamPersistence.update(iceCream, merge);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.reindex(iceCream);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}

		return iceCream;
	}

	/**
	 * Returns the ice cream local service.
	 *
	 * @return the ice cream local service
	 */
	public IceCreamLocalService getIceCreamLocalService() {
		return iceCreamLocalService;
	}

	/**
	 * Sets the ice cream local service.
	 *
	 * @param iceCreamLocalService the ice cream local service
	 */
	public void setIceCreamLocalService(
		IceCreamLocalService iceCreamLocalService) {
		this.iceCreamLocalService = iceCreamLocalService;
	}

	/**
	 * Returns the ice cream remote service.
	 *
	 * @return the ice cream remote service
	 */
	public IceCreamService getIceCreamService() {
		return iceCreamService;
	}

	/**
	 * Sets the ice cream remote service.
	 *
	 * @param iceCreamService the ice cream remote service
	 */
	public void setIceCreamService(IceCreamService iceCreamService) {
		this.iceCreamService = iceCreamService;
	}

	/**
	 * Returns the ice cream persistence.
	 *
	 * @return the ice cream persistence
	 */
	public IceCreamPersistence getIceCreamPersistence() {
		return iceCreamPersistence;
	}

	/**
	 * Sets the ice cream persistence.
	 *
	 * @param iceCreamPersistence the ice cream persistence
	 */
	public void setIceCreamPersistence(IceCreamPersistence iceCreamPersistence) {
		this.iceCreamPersistence = iceCreamPersistence;
	}

	/**
	 * Returns the ice cream documents local service.
	 *
	 * @return the ice cream documents local service
	 */
	public IceCreamDocumentsLocalService getIceCreamDocumentsLocalService() {
		return iceCreamDocumentsLocalService;
	}

	/**
	 * Sets the ice cream documents local service.
	 *
	 * @param iceCreamDocumentsLocalService the ice cream documents local service
	 */
	public void setIceCreamDocumentsLocalService(
		IceCreamDocumentsLocalService iceCreamDocumentsLocalService) {
		this.iceCreamDocumentsLocalService = iceCreamDocumentsLocalService;
	}

	/**
	 * Returns the ice cream documents remote service.
	 *
	 * @return the ice cream documents remote service
	 */
	public IceCreamDocumentsService getIceCreamDocumentsService() {
		return iceCreamDocumentsService;
	}

	/**
	 * Sets the ice cream documents remote service.
	 *
	 * @param iceCreamDocumentsService the ice cream documents remote service
	 */
	public void setIceCreamDocumentsService(
		IceCreamDocumentsService iceCreamDocumentsService) {
		this.iceCreamDocumentsService = iceCreamDocumentsService;
	}

	/**
	 * Returns the ice cream documents persistence.
	 *
	 * @return the ice cream documents persistence
	 */
	public IceCreamDocumentsPersistence getIceCreamDocumentsPersistence() {
		return iceCreamDocumentsPersistence;
	}

	/**
	 * Sets the ice cream documents persistence.
	 *
	 * @param iceCreamDocumentsPersistence the ice cream documents persistence
	 */
	public void setIceCreamDocumentsPersistence(
		IceCreamDocumentsPersistence iceCreamDocumentsPersistence) {
		this.iceCreamDocumentsPersistence = iceCreamDocumentsPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	/**
	 * Returns the d l file entry local service.
	 *
	 * @return the d l file entry local service
	 */
	public DLFileEntryLocalService getDLFileEntryLocalService() {
		return dlFileEntryLocalService;
	}

	/**
	 * Sets the d l file entry local service.
	 *
	 * @param dlFileEntryLocalService the d l file entry local service
	 */
	public void setDLFileEntryLocalService(
		DLFileEntryLocalService dlFileEntryLocalService) {
		this.dlFileEntryLocalService = dlFileEntryLocalService;
	}

	/**
	 * Returns the d l file entry remote service.
	 *
	 * @return the d l file entry remote service
	 */
	public DLFileEntryService getDLFileEntryService() {
		return dlFileEntryService;
	}

	/**
	 * Sets the d l file entry remote service.
	 *
	 * @param dlFileEntryService the d l file entry remote service
	 */
	public void setDLFileEntryService(DLFileEntryService dlFileEntryService) {
		this.dlFileEntryService = dlFileEntryService;
	}

	/**
	 * Returns the d l file entry persistence.
	 *
	 * @return the d l file entry persistence
	 */
	public DLFileEntryPersistence getDLFileEntryPersistence() {
		return dlFileEntryPersistence;
	}

	/**
	 * Sets the d l file entry persistence.
	 *
	 * @param dlFileEntryPersistence the d l file entry persistence
	 */
	public void setDLFileEntryPersistence(
		DLFileEntryPersistence dlFileEntryPersistence) {
		this.dlFileEntryPersistence = dlFileEntryPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("com.ssavr.solr.model.IceCream",
			iceCreamLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.ssavr.solr.model.IceCream");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	protected Class<?> getModelClass() {
		return IceCream.class;
	}

	protected String getModelClassName() {
		return IceCream.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = iceCreamPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = IceCreamLocalService.class)
	protected IceCreamLocalService iceCreamLocalService;
	@BeanReference(type = IceCreamService.class)
	protected IceCreamService iceCreamService;
	@BeanReference(type = IceCreamPersistence.class)
	protected IceCreamPersistence iceCreamPersistence;
	@BeanReference(type = IceCreamDocumentsLocalService.class)
	protected IceCreamDocumentsLocalService iceCreamDocumentsLocalService;
	@BeanReference(type = IceCreamDocumentsService.class)
	protected IceCreamDocumentsService iceCreamDocumentsService;
	@BeanReference(type = IceCreamDocumentsPersistence.class)
	protected IceCreamDocumentsPersistence iceCreamDocumentsPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@BeanReference(type = DLFileEntryLocalService.class)
	protected DLFileEntryLocalService dlFileEntryLocalService;
	@BeanReference(type = DLFileEntryService.class)
	protected DLFileEntryService dlFileEntryService;
	@BeanReference(type = DLFileEntryPersistence.class)
	protected DLFileEntryPersistence dlFileEntryPersistence;
	private static Log _log = LogFactoryUtil.getLog(IceCreamLocalServiceBaseImpl.class);
	private String _beanIdentifier;
}